/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Long
 */
public class RemoteMenuPanelKeoTha extends javax.swing.JPanel {

    /**
     * Creates new form WiimoteMenuPanel
     */
    public RemoteMenuPanelKeoTha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 550));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Manage Remote Setting");
        add(jLabel1);
        jLabel1.setBounds(250, 20, 170, 17);

        jLabel2.setText("Next Image");
        add(jLabel2);
        jLabel2.setBounds(40, 80, 90, 20);

        jLabel3.setText("Previous Image");
        add(jLabel3);
        jLabel3.setBounds(390, 80, 100, 14);

        jLabel4.setText("Roate Clockwise");
        add(jLabel4);
        jLabel4.setBounds(30, 130, 110, 20);

        jLabel5.setText("Rotate Anticlockwise");
        add(jLabel5);
        jLabel5.setBounds(370, 130, 130, 14);

        jLabel6.setText("Zoom In");
        add(jLabel6);
        jLabel6.setBounds(50, 180, 70, 20);

        jButton1.setIcon(new ImageIcon("C:\\Users\\Long\\Dropbox\\Thesis\\Thesis\\src\\Image\\next image.png"));
        jButton1.setBackground(Color.white);
        add(jButton1);
        jButton1.setBounds(150, 70, 110, 40);

        jButton2.setIcon(new ImageIcon("C:\\Users\\Long\\Dropbox\\Thesis\\Thesis\\src\\Image\\rotate clockwise image.png"));
        add(jButton2);
        jButton2.setBounds(150, 120, 110, 40);

        jButton3.setIcon(new ImageIcon("C:\\Users\\Long\\Dropbox\\Thesis\\Thesis\\src\\Image\\zoom in image.png"));
        add(jButton3);
        jButton3.setBounds(150, 170, 110, 40);

        jButton4.setIcon(new ImageIcon("C:\\Users\\Long\\Dropbox\\Thesis\\Thesis\\src\\Image\\previous image.png"));
        add(jButton4);
        jButton4.setBounds(490, 70, 110, 40);

        jButton5.setIcon(new ImageIcon("C:\\Users\\Long\\Dropbox\\Thesis\\Thesis\\src\\Image\\rotate anticlockwise image.png"));
        add(jButton5);
        jButton5.setBounds(490, 120, 110, 40);

        jButton6.setIcon(new ImageIcon("C:\\Users\\Long\\Dropbox\\Thesis\\Thesis\\src\\Image\\zoom out image.png"));
        add(jButton6);
        jButton6.setBounds(490, 170, 110, 40);

        jButton7.setText("Use User's gestures");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(110, 260, 170, 40);

        jButton8.setText("Create User's gestures");
        add(jButton8);
        jButton8.setBounds(400, 260, 170, 40);

        jButton9.setText("OK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9);
        jButton9.setBounds(310, 330, 60, 40);

        jLabel8.setText("Zoom Out");
        add(jLabel8);
        jLabel8.setBounds(410, 180, 70, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
